---
#
# Installing Elasticsearch

- name: Install libsemanage-python and dependencies
  yum:
    name: python3-libsemanage
  become: true

- name: Copy elasticsearch yum repo file
  copy:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install elasticsearch and openjdk
  yum:
    name: [elasticsearch, java-1.8.0-openjdk-headless]
  become: true

# https://www.centos.org/forums/viewtopic.php?t=16398
- name: Obtain exact version of JRE for libjli.so workaround
  shell: "ls /usr/lib/jvm/ | grep java | grep openjdk-1"
  register: libjli_location
  become: true

- name: Apply EL symlink workaround for libjli.so
  file:
    src='/usr/lib/jvm/{{libjli_location.stdout}}/jre/lib/amd64/jli/libjli.so'
    dest='/lib64/libjli.so'
    state=link
  become: true

- name: Setup elasticsearch service to autostart
  service: name=elasticsearch state=started enabled=true
  become: true
