---
# 
# Installing ELK stack using playbook

- hosts: app_server
  remote_user: ec2-user
  vars_files:
    - vars/all.yml
  roles:
    - { role: elasticsearch }
    - { role: logstash }
    - { role: nginx }
    - { role: kibana }
